version: '3'
services:
  db: 
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dirty
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile/rails
    command: puma
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  elasticsearch:
    image: elasticsearch:2.4.6
    ports:
      - "9200:9200"
  kibana:
    build:
      context: .
      dockerfile: ./Dockerfile/kibana
    ports:
      - "5601:5601"
  redis:
    image: redis:3.2.10
